name    'demo'
version '0.1.0'
source 'https://github.com/caess/sysadmin-cucumber-demo/tree/master/puppet-repo/modules/demo'
author 'Chris Ess'
license 'Apache License, Version 2.0'
summary 'Demo environment module'
description 'Module for a demo environment for the blog post "An Introduction To Cucumber For System Administrators"'
project_page 'http://www.ithiriel.com'

## Add dependencies, if any:
dependency 'thias/bind', '>= 0.4.0'
